# Generated by Django 3.2.15 on 2023-10-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=128)),
                ('news_author', models.CharField(max_length=32)),
                ('news_photographer', models.CharField(max_length=32)),
                ('news_category', models.CharField(max_length=1)),
                ('news_content', models.TextField()),
                ('news_photo', models.TextField()),
                ('news_post_datetime', models.CharField(max_length=19)),
                ('news_update_datetime', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('statistic_year', models.CharField(max_length=3)),
                ('statistic_achievement', models.CharField(max_length=5)),
                ('statistic_graduate', models.CharField(max_length=5)),
                ('statistic_team', models.CharField(max_length=5)),
                ('statistic_project', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=128)),
                ('student_password', models.CharField(max_length=64)),
                ('student_photo', models.TextField()),
                ('student_gender', models.CharField(max_length=1)),
                ('student_grade', models.CharField(max_length=10)),
                ('student_birthday', models.CharField(max_length=10)),
                ('student_address', models.TextField()),
                ('student_phone', models.CharField(max_length=11)),
                ('student_email', models.CharField(max_length=64)),
                ('student_github_url', models.TextField()),
                ('student_csdn_url', models.TextField()),
                ('student_proverb', models.TextField()),
                ('student_self_introduction', models.TextField()),
                ('student_major', models.CharField(max_length=64)),
                ('student_achievement', models.TextField()),
                ('student_alive', models.CharField(max_length=1)),
                ('student_status', models.CharField(max_length=1)),
            ],
        ),
    ]
