# Generated by Django 3.2.15 on 2023-10-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_code',
            new_name='news_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_code',
            new_name='student_id',
        ),
    ]
