# Generated by Django 3.2.15 on 2023-10-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0002_auto_20231013_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_address',
        ),
    ]
