# Generated by Django 3.2.15 on 2023-10-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0003_remove_students_student_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
