# Generated by Django 3.2.15 on 2024-01-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0006_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(max_length=32),
        ),
    ]
