# Generated by Django 3.2.15 on 2024-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0007_alter_slider_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_field_content', models.TextField()),
                ('research_field_photo', models.CharField(max_length=128)),
            ],
        ),
    ]
