# Generated by Django 3.2.15 on 2024-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0008_researchfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('thesis_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('thesis_title', models.CharField(max_length=128)),
                ('thesis_author', models.CharField(max_length=32)),
                ('thesis_link', models.CharField(max_length=128)),
                ('thesis_date', models.CharField(max_length=10)),
            ],
        ),
    ]
