# Generated by Django 3.2.15 on 2024-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0009_thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('work_title', models.CharField(max_length=128)),
                ('work_author', models.CharField(max_length=32)),
                ('work_abstract', models.CharField(max_length=256)),
                ('work_link', models.CharField(max_length=128)),
                ('work_date', models.CharField(max_length=10)),
                ('work_photo', models.CharField(max_length=16)),
            ],
        ),
    ]
