# Generated by Django 3.2.15 on 2024-03-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0010_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_alive',
            new_name='student_graduate',
        ),
    ]
