# Generated by Django 3.2.15 on 2024-03-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0011_rename_student_alive_student_student_graduate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
