# Generated by Django 3.2.15 on 2024-04-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabWebApp', '0013_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_major',
            new_name='message_grade',
        ),
    ]
